# Generated by Django 3.0.5 on 2020-06-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False)),
                ('pic', models.ImageField(upload_to='profile')),
            ],
        ),
    ]
